# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import foodchain_pb2 as foodchain__pb2


class MaketxStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.maketx = channel.unary_unary(
        '/Maketx/maketx',
        request_serializer=foodchain__pb2.Transaction.SerializeToString,
        response_deserializer=foodchain__pb2.Transaction.FromString,
        )


class MaketxServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def maketx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MaketxServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'maketx': grpc.unary_unary_rpc_method_handler(
          servicer.maketx,
          request_deserializer=foodchain__pb2.Transaction.FromString,
          response_serializer=foodchain__pb2.Transaction.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Maketx', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
